Add useful setters to ResampleOptions struct
rust-av/ffms2-rs pull request #9
Opened 2020-10-01 10:40 UTC by askoufis

These are fields I need to change for a project I'm working on, and they seem the most useful out of all the resample options anyway.

Changing the sample rate is not currently supported by ffms2
https://github.com/FFMS/ffms2/blob/master/src/core/audiosource.cpp#L201

2020-10-01 13:47 UTC, Luni-4 requested changes
Thank you again! :)

Just a few nits

2020-10-01 13:47 UTC, Luni-4 commented on src/resample.rs
> +        resample.ChannelLayout = channel_layout;
We can reduce to a single line: `self.resample.ChannelLayout = channel.layout`;

2020-10-01 13:47 UTC, Luni-4 commented on src/resample.rs
> +        resample.SampleFormat = SampleFormat::to_sample_format(sample_format);
Same as above: `self.resample.SampleFormat = SampleFormat::to_sample_format(sample_format);`

2020-10-02 04:12 UTC, askoufis commented
Done

2020-10-02 08:06 UTC, Luni-4 approved these changes
Thanks a lot! :)

2020-10-02 08:07 UTC, merged